# .pre-commit-config.yaml

repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # It's good practice to use the latest version.
    # Check for the latest tag here: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5 # Using a recent version as of May 2025
    hooks:
        # 1. Run the linter using the 'check' subcommand.
        #    This hook identifies and can automatically fix linting errors.
        -   id: ruff
            # The 'args' now explicitly show the subcommand being run.
            args: [--fix]

        # 2. Run the formatter using the 'format' subcommand.
        #    This ensures consistent code style.
        -   id: ruff-format